# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
FPGA_UTIL_LAYERDIR := "${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "fpga-util"
BBFILE_PATTERN_fpga-util = "^${LAYERDIR}/"
BBFILE_PRIORITY_fpga-util = "5"

LAYERDEPENDS_fpga-util = "core"
LAYERSERIES_COMPAT_fpga-util = "kirkstone langdale scarthgap"
