# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"
KR260DEMO_LAYERDIR := "${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-kr260demo"
BBFILE_PATTERN_meta-kr260demo = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-kr260demo = "6"

LAYERDEPENDS_meta-kr260demo = " \
    core \
    mncos \
    fpga-util \
    xilinx \
    xilinx-standalone \
    "
LAYERSERIES_COMPAT_meta-kr260demo = "kirkstone langdale scarthgap"

require conf/xilinx-zynqmp-openamp.conf
